# Generated by Django 5.2.11 on 2026-02-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='rame rame rame'),
            preserve_default=False,
        ),
    ]
